version: '3.8'

services:
    app:
        build:
            context: Docker
            dockerfile: ./Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "8888:80"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - petshop-net
        depends_on:
            - mysql
    # Serviço MySQL
    mysql:
        image: mysql/mysql-server:8.0
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "33306:3306"
        volumes:
            - './Docker/test-db.sh:/docker-entrypoint-initdb.d/10-test-db.sh'
        networks:
            - petshop-net
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
networks:
    petshop-net:
        driver: bridge